// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/golang/mock/sample/concurrent (interfaces: Math)

// Package mock_concurrent is a generated GoMock package.
package mock_concurrent

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMath is a mock of Math interface
type MockMath struct {
	ctrl     *gomock.Controller
	recorder *MockMathMockRecorder
}

// MockMathMockRecorder is the mock recorder for MockMath
type MockMathMockRecorder struct {
	mock *MockMath
}

// NewMockMath creates a new mock instance
func NewMockMath(ctrl *gomock.Controller) *MockMath {  // 新建 mockxxx
	mock := &MockMath{ctrl: ctrl}
	mock.recorder = &MockMathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMath) EXPECT() *MockMathMockRecorder {
	return m.recorder
}

// Sum mocks base method
func (m *MockMath) Sum(arg0, arg1 int) int { //math 的 mock 必须实现的方法 Sum
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", arg0, arg1) //Sum 的 mock,此处查表并调用 Call,action
	ret0, _ := ret[0].(int)
	return ret0
C

// Sum indicates an expected call of Sum
func (mr *MockMathMockRecorder) Sum(arg0, arg1 interface{}) *gomock.Call { //新建 Call
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockMath)(nil).Sum), arg0, arg1)	//新建 Call 传入了 mock
}
